# -*- coding: utf-8 -*-
"""Sistema Completo Metro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4vKPOSUXjBsM3gFhRaJPM1zhMqgmNfA
"""

import time
from gpiozero import LED, AngularServo, Buzzer
from RPLCD.i2c import CharLCD
from mfrc522 import SimpleMFRC522
import RPi.GPIO as GPIO

# --- CONFIGURACIÓN DE PINES ---
PIN_LED_ROJO = 17
PIN_LED_VERDE = 27
PIN_SERVO_1 = 12
PIN_SERVO_2 = 13
# PIN_LASER = 22  # Descomentar cuando tengas el sensor láser
# PIN_BUZZER = 23 # Descomentar cuando tengas el zumbador

# --- OBJETOS DE HARDWARE ---
led_rojo = LED(PIN_LED_ROJO)
led_verde = LED(PIN_LED_VERDE)

# Configuramos servos
s1 = AngularServo(PIN_SERVO_1, min_angle=0, max_angle=180, min_pulse_width=0.0005, max_pulse_width=0.0024)
s2 = AngularServo(PIN_SERVO_2, min_angle=0, max_angle=180, min_pulse_width=0.0005, max_pulse_width=0.0024)

# Lector RFID
reader = SimpleMFRC522()

# Pantalla LCD (Intentamos conectar, si falla seguimos sin ella para no romper el programa)
try:
    lcd = CharLCD(i2c_expander='PCF8574', address=0x27, port=1, cols=16, rows=2, dotsize=8)
except:
    lcd = None
    print("AVISO: LCD no detectada. Usando solo consola.")

# --- FUNCIONES ---

def sonar_zumbador():
    """Simula el pitido corto"""
    print("* BEEP *")
    # Cuando tengas el buzzer:
    # buzzer.on()
    # time.sleep(0.2)
    # buzzer.off()

def mensaje_pantalla(linea1, linea2=""):
    """Escribe en la LCD y en la consola"""
    print(f"LCD: {linea1} | {linea2}")
    if lcd:
        lcd.clear()
        lcd.write_string(linea1)
        lcd.cursor_pos = (1, 0)
        lcd.write_string(linea2)

def abrir_puertas():
    """Secuencia de apertura"""
    sonar_zumbador()
    led_rojo.off()
    led_verde.on()
    mensaje_pantalla("ACCESO PERMITIDO", "Pase por favor")

    # Girar servos 90 grados
    s1.angle = 90
    s2.angle = 90
    time.sleep(0.5) # Tiempo para que los motores lleguen

def cerrar_puertas():
    """Secuencia de cierre"""
    mensaje_pantalla("Cerrando...", "Puerta Metro")
    led_verde.off()
    led_rojo.on()

    # Girar servos a posición inicial
    s1.angle = 0
    s2.angle = 180 # Espejo
    time.sleep(1)
    mensaje_pantalla("ESPERANDO", "TARJETA...")

def esperar_paso_persona():
    """
    Aquí iría la lógica del sensor láser.
    Como aún no lo tienes, simulamos que la persona tarda
    5 segundos en cruzar.
    """
    print("Esperando a que cruce la persona (Simulación 5s)...")

    # --- MODO SIMULACIÓN ---
    time.sleep(5)

    # --- MODO REAL (Cuando tengas el láser) ---
    # Supongamos que el láser da un 1 (True) si no hay nada, y 0 (False) si alguien corta el haz
    # while GPIO.input(PIN_LASER) == True:
    #     time.sleep(0.1)
    # print("Persona detectada cruzando!")
    # while GPIO.input(PIN_LASER) == False:
    #    time.sleep(0.1)
    # print("La persona ha terminado de cruzar.")

# --- BUCLE PRINCIPAL ---

def main():
    try:
        # Estado inicial
        cerrar_puertas()

        while True:
            # 1. Leer tarjeta
            id, text = reader.read()
            print(f"Tarjeta detectada: {id}")

            # Aquí podrías poner un 'if' para ver si la tarjeta es válida
            # Por ahora, aceptamos todas.

            # 2. Abrir Puerta
            abrir_puertas()

            # 3. Esperar a que pase (Sensor Láser)
            esperar_paso_persona()

            # 4. Cerrar Puerta
            cerrar_puertas()

    except KeyboardInterrupt:
        print("\nApagando sistema...")
        if lcd: lcd.clear()
        GPIO.cleanup()

if __name__ == "__main__":
    main()