# -*- coding: utf-8 -*-
"""Prueba LEDs y Servos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxKutla6IdBBn0YOKTXNMOd3LKqj6U4U
"""

from gpiozero import LED, AngularServo
from time import sleep

# --- CONFIGURACIÓN ---
# Pines GPIO (Broadcom numbering)
PIN_LED_ROJO = 17
PIN_LED_VERDE = 27
PIN_SERVO_1 = 12
PIN_SERVO_2 = 13

print("Iniciando prueba de componentes básicos...")

# 1. Configurar LEDs
led_rojo = LED(PIN_LED_ROJO)
led_verde = LED(PIN_LED_VERDE)

# 2. Configurar Servos
# Los servos SG90 suelen trabajar con un ancho de pulso entre 0.0005 y 0.0024 aprox
# Si el servo vibra mucho o no llega al final, ajusta min_pulse_width y max_pulse_width
servo1 = AngularServo(PIN_SERVO_1, min_angle=0, max_angle=180, min_pulse_width=0.0005, max_pulse_width=0.0024)
servo2 = AngularServo(PIN_SERVO_2, min_angle=0, max_angle=180, min_pulse_width=0.0005, max_pulse_width=0.0024)

try:
    while True:
        print("--- Estado: CERRADO (Rojo ON) ---")
        led_rojo.on()
        led_verde.off()

        # Mover servos a posición cerrada (0 grados)
        servo1.angle = 0
        servo2.angle = 180 # El segundo servo suele ir invertido si están frente a frente
        sleep(2)

        print("--- Estado: ABIERTO (Verde ON) ---")
        led_rojo.off()
        led_verde.on()

        # Mover servos a posición abierta (90 grados)
        servo1.angle = 90
        servo2.angle = 90
        sleep(2)

except KeyboardInterrupt:
    print("\nPrueba finalizada.")
    led_rojo.off()
    led_verde.off()
    # En gpiozero los servos se limpian solos al salir