# -*- coding: utf-8 -*-
"""Prueba RFID y LCD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpVwJF58ASiEy_97yi9q27Wb2WGgDH55
"""

import time
from RPLCD.i2c import CharLCD
from mfrc522 import SimpleMFRC522
import RPi.GPIO as GPIO

# --- CONFIGURACIÓN ---
# IMPORTANTE: Asegúrate de tener I2C y SPI habilitados en raspi-config

print("Iniciando prueba de LCD y RFID...")

# 1. Configurar Pantalla LCD
# A veces la dirección es 0x27 o 0x3f. Usa 'i2cdetect -y 1' en terminal si falla.
try:
    lcd = CharLCD(i2c_expander='PCF8574', address=0x27, port=1, cols=16, rows=2, dotsize=8)
    lcd.clear()
    lcd.write_string('Iniciando...')
    time.sleep(1)
except Exception as e:
    print(f"Error con la LCD (verifica la dirección I2C): {e}")
    lcd = None

# 2. Configurar Lector RFID
reader = SimpleMFRC522()

print("Acerca una tarjeta al lector...")
if lcd:
    lcd.clear()
    lcd.write_string('Escanea Tarjeta')

try:
    while True:
        # Lectura de tarjeta (esto pausa el código hasta que detecta una)
        id, text = reader.read()

        print(f"ID Detectado: {id}")

        if lcd:
            lcd.clear()
            lcd.write_string(f"ID: {id}")
            lcd.cursor_pos = (1, 0)
            lcd.write_string("Detectado!")

        # Pequeña pausa para no leer la misma tarjeta 100 veces por segundo
        time.sleep(2)

        if lcd:
            lcd.clear()
            lcd.write_string('Escanea Tarjeta')

except KeyboardInterrupt:
    print("\nSalida.")
    if lcd:
        lcd.clear()
    GPIO.cleanup()